apiVersion: v1
kind: ConfigMap
metadata:
  name: analise-config
  labels:
    app.kubernetes.io/name: analise
    app.kubernetes.io/part-of: agrosolutions-platform
data:
  Logging__LogLevel__Default: Information
  Identity__BaseUrl: http://analise
