apiVersion: apps/v1
kind: Deployment
metadata:
  name: analise
  labels:
    app.kubernetes.io/name: analise
    app.kubernetes.io/part-of: agrosolutions-platform
    app.kubernetes.io/component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: analise
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analise
        app.kubernetes.io/part-of: agrosolutions-platform
        app.kubernetes.io/component: api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: analise
          image: analise
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: agrosolutions-auth-secrets
            - configMapRef:
                name: analise-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
          env:
            - name: RabbitMq__UserName
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-collector:4317"
          # Se tiver segredos (JWT keys, connection strings), use Secret (n√£o ConfigMap)
          # envFrom:
          #   - secretRef:
          #       name: analise-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
