apiVersion: v1
kind: ConfigMap
metadata:
  name: propriedades-config
  labels:
    app.kubernetes.io/name: propriedades
    app.kubernetes.io/part-of: agrosolutions-platform
data:
  Logging__LogLevel__Default: Information
  Identity__BaseUrl: http://propriedades
  Db__AutoMigrate: "true"
