apiVersion: v1
kind: Service
metadata:
  name: propriedades
  labels:
    app.kubernetes.io/name: propriedades
    app.kubernetes.io/part-of: agrosolutions-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: propriedades
  ports:
    - name: http
      port: 80
      targetPort: http
