apiVersion: v1
kind: ConfigMap
metadata:
  name: analise-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: "Server=sql-service;Database=AgroSolutionsAnalise;User Id=sa;Password=Fi@p2026;TrustServerCertificate=True;"
  SqlServer__ConnectionString: "Server=sql-service;Database=AgroSolutionsAnalise;User Id=sa;Password=Fi@p2026;TrustServerCertificate=True;"
  OpenTelemetry__Enabled: "true"
  OpenTelemetry__Endpoint: "http://otel-collector:4317"
  Jwt__Key: "segredo_super_secreto_para_desenvolvimento_local"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
  RabbitMq__HostName: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__UserName: "user"
  RabbitMq__Password: "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestao-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: "Server=sql-service;Database=AgroSolutionsIngestao;User Id=sa;Password=Fi@p2026;TrustServerCertificate=True;"
  SqlServer__ConnectionString: "Server=sql-service;Database=AgroSolutionsIngestao;User Id=sa;Password=Fi@p2026;TrustServerCertificate=True;"
  Services__PropriedadesUrl: "http://propriedades"
  SqlServer__UseInMemory: "false"
  RabbitMq__Enabled: "true"
  RabbitMq__HostName: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__UserName: "user"
  RabbitMq__Password: "password"
  OpenTelemetry__Enabled: "false"
  OpenTelemetry__Endpoint: "http://otel-collector:4317"
  # Para o Simulador (que l variveis tambm)
  OpenTelemetry_Enabled: "false"
  OpenTelemetry_Endpoint: "http://otel-collector:4317"
  Jwt__Key: "segredo_super_secreto_para_desenvolvimento_local"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: propriedades-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: "Server=sql-service;Database=AgroSolutionsPropriedades;User Id=sa;Password=Fi@p2026;TrustServerCertificate=True;"
  OpenTelemetry__Enabled: "true"
  OpenTelemetry__Endpoint: "http://otel-collector:4317"
  Jwt__Key: "segredo_super_secreto_para_desenvolvimento_local"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: usuarios-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: "Server=sql-service;Database=AgroSolutionsUsuarios;User Id=sa;Password=Fi@p2026;TrustServerCertificate=True;"
  SqlServer__UseInMemory: "false"
  OpenTelemetry__Enabled: "true"
  OpenTelemetry__Endpoint: "http://otel-collector:4317"
  Jwt__Key: "segredo_super_secreto_para_desenvolvimento_local"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
