apiVersion: v1
kind: ConfigMap
metadata:
  name: analise-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  OpenTelemetry__Enabled: "true"
  OpenTelemetry__Endpoint: "http://jaeger-collector:4317"
  Jwt__Key: "segredo_super_secreto_para_desenvolvimento_local"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestao-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  SqlServer__UseInMemory: "true"
  RabbitMq__Enabled: "false"
  OpenTelemetry__Enabled: "true"
  OpenTelemetry__Endpoint: "http://jaeger-collector:4317"
  # Para o Simulador (que l variveis tambm)
  OpenTelemetry_Enabled: "true"
  OpenTelemetry_Endpoint: "http://jaeger-collector:4317"
  Jwt__Key: "segredo_super_secreto_para_desenvolvimento_local"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: propriedades-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  OpenTelemetry__Enabled: "true"
  OpenTelemetry__Endpoint: "http://jaeger-collector:4317"
  Jwt__Key: "segredo_super_secreto_para_desenvolvimento_local"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: usuarios-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  OpenTelemetry__Enabled: "true"
  OpenTelemetry__Endpoint: "http://jaeger-collector:4317"
  Jwt__Key: "segredo_super_secreto_para_desenvolvimento_local"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
  SqlServer__UseInMemory: "true"

