apiVersion: v1
kind: Service
metadata:
  name: usuarios
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: propriedades
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: ingestao
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: analise
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30004
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30005
  - name: management
    port: 15672
    targetPort: 15672
    nodePort: 30006
