apiVersion: v1
kind: Service
metadata:
  name: usuarios
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: propriedades
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: ingestao
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: analise
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30004
