apiVersion: v1
kind: Service
metadata:
  name: usuarios
  namespace: agrosolutions-local
  labels:
    app: usuarios
    monitoring: enabled

apiVersion: v1
kind: Service
metadata:
  name: propriedades
  namespace: agrosolutions-local
  labels:
    app: propriedades
    monitoring: enabled

apiVersion: v1
kind: Service
metadata:
  name: ingestao
  namespace: agrosolutions-local
  labels:
    app: ingestao
    monitoring: enabled

apiVersion: v1
kind: Service
metadata:
  name: analise
  namespace: agrosolutions-local
  labels:
    app: analise
    monitoring: enabled
