apiVersion: v1
kind: Service
metadata:
  name: usuarios
  labels:
    app: usuarios
    monitoring: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: propriedades
  labels:
    app: propriedades
    monitoring: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: ingestao
  labels:
    app: ingestao
    monitoring: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: analise
  labels:
    app: analise
    monitoring: enabled
