apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agrosolutions-apis
  namespace: agrosolutions-observability
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - agrosolutions-prod

  selector:
    matchLabels:
      monitoring: enabled
      app.kubernetes.io/part-of: agrosolutions-platform

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
