apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestao-config
  labels:
    app.kubernetes.io/name: ingestao
    app.kubernetes.io/part-of: agrosolutions-platform
data:
  Logging__LogLevel__Default: Information
  Identity__BaseUrl: http://ingestao
