apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus-service:9090
  isDefault: true
- name: SQLServer
  type: mssql
  uid: mssql-analise
  url: sql-service
  user: sa
  secureJsonData:
    password: ${SQL_PASSWORD}
  jsonData:
    database: AgroSolutionsAnalise
    encrypt: disable
- name: Jaeger
  type: jaeger
  uid: jaeger
  access: proxy
  url: http://jaeger-collector:16686
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  jsonData:
    derivedFields:
      - datasourceUid: jaeger
        matcherRegex: '(?:TraceId|@tr)":"(\w+)"'
        name: TraceID
        url: $${__value.raw}
