apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus-service:9090
  isDefault: true
- name: SQLServer
  type: mssql
  uid: mssql-analise
  url: sql-service
  user: sa
  secureJsonData:
    password: ${SQL_PASSWORD}
  jsonData:
    database: AgroSolutionsAnalise
    encrypt: disable
