apiVersion: v1
kind: Secret
metadata:
  name: agrosolutions-auth-secrets
type: Opaque
stringData:
  Jwt__Key: "SuaChaveSuperSecretaDePeloMenos32Caracteres"
  Jwt__Issuer: "AgroSolutions"
  Jwt__Audience: "AgroSolutions"
