apiVersion: v1
kind: ConfigMap
metadata:
  name: usuarios-config
  labels:
    app.kubernetes.io/name: usuarios
    app.kubernetes.io/part-of: agrosolutions-platform
data:
  Logging__LogLevel__Default: Information
  Identity__BaseUrl: http://usuarios