apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agrosolutions-prod
resources:
- namespace.yaml
- monitoring/servicemonitors.yaml
- ../../base/analise
- ../../base/ingestao
- ../../base/propriedades
- ../../base/usuarios
- ../../base/observability
- ../../base/sqlserver-deployment.yaml
- ../../base/db-init-job.yaml
- ../../rabbitmq

images:
- name: analise
  newName: ajmarzola/agrosolutions-analise
  newTag: 1.0.0
- name: ingestao
  newName: ajmarzola/agrosolutions-ingestao
  newTag: 1.0.0
- name: ingestao-simulador
  newName: ajmarzola/agrosolutions-ingestao-simulador
  newTag: 1.0.0
- name: propriedades
  newName: ajmarzola/agrosolutions-propriedades
  newTag: 1.0.0
- name: usuarios
  newName: ajmarzola/agrosolutions-usuarios
  newTag: 1.0.0

labels:
- pairs:
    app.kubernetes.io/part-of: agrosolutions-platform
    app.kubernetes.io/managed-by: kustomize
    env: prod

patchesStrategicMerge:
- configmap-env-patch.yaml
- monitoring/service-labels.patch.yaml
- db-resources.patch.yaml
- rabbitmq-resources.patch.yaml
