name: AgroSolutions.Analise.WebApi CI
on:
  push:
    paths:
    - src/services/AgroSolutions.Analise/AgroSolutions.Analise.WebApi/**
    - .github/workflows/**
  pull_request:
    paths:
    - src/services/AgroSolutions.Analise/AgroSolutions.Analise.WebApi/**
    - .github/workflows/**
jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci-reusable.yml
    with:
      solution_path: AgroSolutions.slnx
      dotnet_version: "10.0.x"
