name: AgroSolutions.Ingestao.WebApi CI
true:
  push:
    paths:
    - src/services/AgroSolutions.Ingestao/AgroSolutions.Ingestao.WebApi/**
    - .github/workflows/**
  pull_request:
    paths:
    - src/services/AgroSolutions.Ingestao/AgroSolutions.Ingestao.WebApi/**
    - .github/workflows/**
jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci-reusable.yml
    with:
      solution_path: AgroSolutions.slnx
