name: AgroSolutions.Ingestao.WebApi CI

on:
  push:
    paths:
      - "src/services/AgroSolutions.Ingestao/AgroSolutions.Ingestao.WebApi/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/services/AgroSolutions.Ingestao/AgroSolutions.Ingestao.WebApi/**"
      - ".github/workflows/**"

jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci-reusable.yml
    with:
      project_path: src/services/AgroSolutions.Ingestao/AgroSolutions.Ingestao.WebApi/AgroSolutions.Ingestao.WebApi.csproj
