name: AgroSolutions.Propriedades.WebApi CI

on:
  push:
    paths:
      - "src/services/AgroSolutions.Propriedades/AgroSolutions.Propriedades.WebApi/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/services/AgroSolutions.Propriedades/AgroSolutions.Propriedades.WebApi/**"
      - ".github/workflows/**"

jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci-reusable.yml
    with:
      project_path: src/services/AgroSolutions.Propriedades/AgroSolutions.Propriedades.WebApi/AgroSolutions.Propriedades.WebApi.csproj
